<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Email' => '',
    'Error, please retry. Your message has not been sent' => '',
    'Genuine and delicious' => '',
    'Is not a phone number' => '',
    'email' => '',
    'Бесплатно' => 'Free',
    'Благодарим за понимание' => 'Thank you for understanding',
    'Блюд на сумму' => 'Dishes for the amount',
    'Бронь' => 'Reservation',
    'В магазин' => 'Shop',
    'Ваш заказ' => 'Your order',
    'Вернуться в корзину' => 'Back to cart',
    'Внимание' => 'Attention',
    'Время' => 'Time',
    'Вы можете овормить заказ на доставку сейчас и мы свяжемся с Вами в рабочее время.'
        => 'You can submit your order for delivery now and we will contact you during business hours.',
    'Далее' => 'Next',
    'Данные для доставки' => 'Delivery info',
    'Дата' => 'Date',
    'Действия' => 'Action',
    'Для доступа необходимо подтвердить совершеннолетний возраст.' => 'To access, you must confirm the age of majority.',
    'Добавить' => 'Add',
    'Добро пожаловать.' => 'Welcome',
    'Дом' => 'Bilding',
    'Доставка' => 'Delivery',
    'Доставка заказов осуществляется ежедневно с 12:30 до 23:00.' => 'Orders are delivered daily from 12:30 to 23:00.',
    'Доставка работает с 12:00 до 22:00' => 'Delivery works from 12:00 to 22:00',
    'Забронировать' => 'Reserve',
    'Заказать' => 'To order',
    'Имя' => 'Name',
    'Все' => 'All',
    'Сообщение' => 'Message',
    'Итого' => 'Summa',
    'Категории' => 'Categories',
    'Квартира' => 'Flat',
    'Кол-во гостей' => 'Guests number',
    'Количество' => 'Count',
    'Комментарий' => 'Comments',
    'Комментарий к заказу' => 'Order comments',
    'Контакты' => 'Contacts',
    'Лента' => 'News',
    'Минимальная сумма заказа 1500' => 'Minimum order amount 1500',
    'Минимальная сумма заказа {0} ₽' => 'Minimum order amount {0} ₽',
    'Мне исполнилось 18 лет' => 'I turned 18',
    'Нажимая на кнопку "Заказать" вы даете согласие на обработку ваших персональных данных, данные
                        будут использованны исключительно для доставки вашего заказа'
        => 'By clicking on the "Order" button you consent to the processing of your personal data, data
                         will be used exclusively for the delivery of your order',
    'Наименование' => 'Name',
    'Отправить сообщение' => 'Send a message',
    'Подробнее' => 'Details',
    'Подъезд' => 'Porch',
    'Приносим свои извинения' => 'We apologize',
    'Разделы' => 'Sections',
    'Оформить заказ' => 'Checkout',
    'Сайт содержит информацию для лиц совершеннолетнего возраста.' => 'The site contains information for adults.',
    'Сведения, размещенные на сайте, не являются рекламой, носят исключительно'
        => 'The information posted on the site is not an advertisement, it is used exclusively',
    'Случаные публикации' => 'Occasional publications',
    'Сумма' => 'Sum',
    'Телефон' => 'Phone',
    'Удалить' => 'Remove',
    'Улица' => 'Street',
    'Цена' => 'Price',
    'Читать далее' => 'Read more',
    'Этаж' => 'Floor',
    'информационный характер, и предназначены только для личного использования.'
        => 'informational character, and are intended for personal use only.',
];